export const AppTexts = {
  ADD: "Add",
  ADD_NEW: "Add New",
  ADD_NOTE: "Add Note",
  ADD_NEW_NOTE: "Add new note",
  CANCEL: "Cancel",
  DELETE: "Delete",
  DELETE_NOTE: "Delete Note",
  EDIT: "Edit",
  EDIT_NOTE: "Edit your note",
  EMPTY: "Empty note",
  NO_NOTES: "No notes yet",
  NOTES: "Notes",
  PLACEHOLDER_TITLE: "Add a note to keep track of your learnings",
  SEARCH: "Search notes",
  SURE_TO_DELETE: "Are you sure you want to delete this note?",
  UNTITLED: "Untitled Note",
  YOUR_NOTE: "Your note",
};
